# Generated by Django 5.1.4 on 2024-12-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_freegame_alter_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='freegame',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
